language: java
jdk: oraclejdk8
sudo: required
dist: trusty
branches:
  only:
  - master
  - 2.1
  - 1.2
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf "$HOME/.m2/repository/com/sheremetov/*
